name: workflowCI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      working-directory: ./java2
      run: | 
        mvn clean install
        mvn clean package
        java -jar target/NRDS-1.0-SNAPSHOT-jar-with-dependencies.jar
        java -jar target/NRDS-1.0-SNAPSHOT-jar-with-dependencies.jar -cli
        mvn clean test
