name: workflowCI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      working-directory: Java2
      run: |
        mvn clean install
        mvn clean package
        java -jar target/NRDS-1.0-SNAPSHOT-jar-with-dependencies.jar
        java -jar target/NRDS-1.0-SNAPSHOT-jar-with-dependencies.jar -cli
        mvn clean test
